[package]
name = "rusty_order_service"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.39", features = ["serde"] }
thiserror = "2.0.11"
uuid = { version = "1.13.1", features = ["v4"] }
